trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '97f32efa-e652-48a0-a886-2e821745401c'
  imageRepository: 'deviprasadazdevpractice'
  containerRegistry: 'prasad3722.azurecr.io'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(imageRepository)
        dockerfile: 'Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    # Publish the Kubernetes manifests folder as a build artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'manifests'       # relative path in repo where your k8s manifests are
        ArtifactName: 'manifests'        # name of artifact
        publishLocation: 'Container'
