#hello
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
        name: cicd
        labels:
          app: cicd
    spec:
      containers:
      - name: cicd
        image: prasad3722.azurecr.io/myimage:latest

        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-auth
